Repository blockful-io/trustful-zuzalu, pull requests merged in 2024-07, with the labels that each got.

#43 feat/style: application
  src/components/01-atoms/DropdownProfile.tsx
  src/components/01-atoms/TheFooterNavbar.tsx
  src/components/01-atoms/TheHeaderMenu.tsx
  src/components/04-templates/BadgeDetailsSection.tsx
  src/components/04-templates/GiveBadgeSection.tsx
  src/components/04-templates/PreCheckinSection.tsx
Labels: type: feature request

#44 fix: give badge
  README.md
  src/components/01-atoms/BadgeDetailsNavigation.tsx
  src/components/01-atoms/TheFooterBadgeDetails.tsx
  src/components/01-atoms/index.ts
  src/components/04-templates/GiveBadgeSection.tsx
  src/hooks/useNotify.ts
  src/lib/client/constants.ts
  src/lib/service/allowedAttestationTitles.ts
  src/lib/service/attest.ts
  src/lib/service/checkedOutVillagers.ts
  src/lib/service/revoke.ts
  src/lib/service/schemas.ts
  src/lib/service/setAttestationTitle.ts
  src/lib/service/setSchema.ts
Labels: type: bug

#45 feat: optimizations on the give badge
  package.json
  src/components/01-atoms/BadgeDetailsNavigation.tsx
  src/components/01-atoms/icons/LoadingIndicator.tsx
  src/components/01-atoms/index.ts
  src/components/04-templates/GiveBadgeSection.tsx
  src/lib/client/constants.ts
  yarn.lock
Labels: type: enhancement

#41 feat: fetch schemas data
  src/components/04-templates/PreCheckinSection.tsx
  src/hooks/useFetchEASData.ts
  src/lib/client/schema_queries.ts
  src/lib/service/hasRole.ts
Labels: type: feature request

#46 refactor: enabling roles accordingly to access control
  src/components/04-templates/GiveBadgeSection.tsx
  src/lib/client/constants.ts
  src/lib/service/hasRole.ts
Labels: type: enhancement

#58 feat: redirecting user to home when disconnecting wallet
  src/components/01-atoms/DropdownProfile.tsx
  src/lib/context/WalletContext.tsx
Labels: type: enhancement

#122 fix: ens name
  .env.example
  .env.local.sample
  .env.sample
  next.config.js
  package.json
  src/components/04-templates/GiveBadgeSection.tsx
  src/hooks/useEnsData.ts
  src/lib/service/fetchENSData.ts
  yarn.lock
Labels: type: bug, status: confirmed
